# Generated by Django 5.2.4 on 2026-02-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mxauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captchamodel",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
